MODE: 'training'
EVAL_TYPE: 'proposal'
DATASET: 'anet'
USE_ENV: True
USE_AGENT: True
USE_OBJ: True
EVAL_SCORE: 'AUC'
GPU_IDS: [0]
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 10
  BATCH_SIZE: 1
  # STEP_PERIOD: 4
  LR: 0.0001
  LOG_DIR: 'runs/c3d_runs_obj_CLIP_v1/'
  ATTENTION_STEPS : 100
VAL:
  SPLIT: 'validation'
  BATCH_SIZE: 1
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 1
  CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/anet_test/checkpoint_26/best_mAP.pth'  ## test tum lum
DATA:
  ANNOTATION_FILE: '/home/tqsang/datasets/activitynet/annotations/activity_net.v1-3.min.json'
  ENV_FEATURE_DIR: '/home/tqsang/datasets/activitynet/c3d_env_features/'
  AGENT_FEATURE_DIR: '/home/tqsang/datasets/activitynet/c3d_agent_features/'
  OBJ_FEATURE_DIR: '/data/tqsang/CLIP_output_ft/'
  RESULT_PATH: 'results/results.json'
  FIGURE_PATH: 'results/results.pdf'
  TEMPORAL_DIM: 100
  MAX_DURATION: 100
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/c3d_checkpoints_obj_CLIP_v1/scores.json'
  CHECKPOINT_DIR: 'checkpoints/anet_test/'
  ENV_DIM: 2048
  AGENT_DIM: 2048
  OBJ_DIM: 512
  ENV_HIDDEN_DIM: 400
  AGENT_HIDDEN_DIM: 400
  OBJ_HIDDEN_DIM: 400
  FEAT_DIM: 400
  TRANSFORMER_DIM: 400
  TOPK_AGENTS: 4
BMN:
  POST_PROCESS:
    MAX_PROPOSALS: 100
    USE_HARD_NMS: False
    SOFT_NMS_ALPHA: 0.4
    SOFT_NMS_LOW_THRESHOLD: 0.
    SOFT_NMS_HIGH_THRESHOLD: 0.
# BMN:
#   POST_PROCESS:
#     MAX_PROPOSALS: 3000
#     USE_HARD_NMS: False
#     HARD_NMS_THRESHOLD: 0.4
#     SOFT_NMS_ALPHA: 0.4
#     SOFT_NMS_LOW_THRESHOLD: 0.65
#     SOFT_NMS_HIGH_THRESHOLD: 0.65
