MODE: 'training'
EVAL_TYPE: 'detection'
DATASET: 'anet'
USE_ENV: True
USE_AGENT: True
USE_OBJ: True
EVAL_SCORE: 'mAP'
GPU_IDS: [0,1,2,3]
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 10
  BATCH_SIZE: 16
  # STEP_PERIOD: 4
  LR: 0.0001
  LOG_DIR: 'runs/c3d_runs_obj_CLIP_v1_det/'
VAL:
  SPLIT: 'validation'
  BATCH_SIZE: 16
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 16
  CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/c3d_checkpoints_obj_CLIP_v1/checkpoint_1/best_AUC.pth'
DATA:
  ANNOTATION_FILE: '/home/tqsang/datasets/activitynet/annotations/activity_net.v1-3.min.json'
  ENV_FEATURE_DIR: '/home/tqsang/datasets/activitynet/c3d_env_features/'
  AGENT_FEATURE_DIR: '/home/tqsang/datasets/activitynet/c3d_agent_features/'
  OBJ_FEATURE_DIR: '/data/tqsang/CLIP_output_ft/'
  RESULT_PATH: 'results/results.json'
  FIGURE_PATH: 'results/results.pdf'
  TEMPORAL_DIM: 100
  MAX_DURATION: 100
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/c3d_checkpoints_obj_CLIP_v1_det/scores.json'
  CHECKPOINT_DIR: 'checkpoints/c3d_checkpoints_obj_CLIP_v1_det/'
  ENV_DIM: 2048
  AGENT_DIM: 2048
  OBJ_DIM: 512
  ENV_HIDDEN_DIM: 2048
  AGENT_HIDDEN_DIM: 2048
  OBJ_HIDDEN_DIM: 2048
  FEAT_DIM: 2048
  TRANSFORMER_DIM: 1024
  TOPK_AGENTS: 4
BMN:
  POST_PROCESS:
    MAX_PROPOSALS: 500
    USE_HARD_NMS: False
    SOFT_NMS_ALPHA: 0.4
    SOFT_NMS_LOW_THRESHOLD: 0.
    SOFT_NMS_HIGH_THRESHOLD: 0.
