MODE: 'validation'
EVAL_TYPE: 'detection'
DATASET: 'anet'
USE_ENV: True
USE_AGENT: True 
EVAL_SCORE: 'mAP'
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 10
  BATCH_SIZE: 16
  LR: 0.0001
  LOG_DIR: 'runs/c3d_det_runs/'
VAL:
  SPLIT: 'validation'
  BATCH_SIZE: 32
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 32
  #CHECKPOINT_PATH: 'checkpoints/best_checkpoints/best_han_anet_c3d/best_AUC.pth'
  CHECKPOINT_PATH: 'checkpoints/c3d_checkpoints/checkpoint_55/best_AUC.pth'
DATA:
  ANNOTATION_FILE: '../datasets/activitynet/annotations/activity_net.v1-3.min.json'
  ENV_FEATURE_DIR: '../datasets/activitynet/c3d_env_features/'
  AGENT_FEATURE_DIR: '../datasets/activitynet/c3d_agent_features/'
  RESULT_PATH: 'results/results.json'
  FIGURE_PATH: 'results/results.pdf'
  TEMPORAL_DIM: 100
  MAX_DURATION: 100
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/c3d_det_checkpoints/scores.json'
  CHECKPOINT_DIR: 'checkpoints/c3d_det_checkpoints/'
  ENV_DIM: 2048
  AGENT_DIM: 2048
  #ENV_HIDDEN_DIM: 2048
  #AGENT_HIDDEN_DIM: 2048
  FEAT_DIM: 2048
  TRANSFORMER_DIM: 1024
  TOPK_AGENTS: 4
BMN:
  POST_PROCESS:
    MAX_PROPOSALS: 500
    USE_HARD_NMS: False
    SOFT_NMS_ALPHA: 0.4
    SOFT_NMS_LOW_THRESHOLD: 0.
    SOFT_NMS_HIGH_THRESHOLD: 0.
