MODE: 'validation'
EVAL_TYPE: 'detection'
DATASET: 'thumos'
USE_ENV: True
USE_AGENT: True
GPU_IDS: [0, 1, 2, 3]
EVAL_SCORE: 'mAP'
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 20
  BATCH_SIZE: 16
  STEP_PERIOD: 1
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  LOG_DIR: 'runs/thumos_c3d_runs/'
VAL:
  SPLIT: 'testing'
  BATCH_SIZE: 32
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 32
  #CHECKPOINT_PATH: 'checkpoints/thumos_c3d_checkpoints/checkpoint_13/best_AR@100.pth'
  CHECKPOINT_PATH: 'checkpoints/best_checkpoints/best_thumos14_final/best_AR@100.pth'
DATA:
  ANNOTATION_FILE: '../datasets/new_thumos14/thumos_annotations/thumos_annotations_09.json'
  DETECTION_GT_FILE: '../datasets/thumos14/thumos_annotations/thumos_det_gt.json'
  ENV_FEATURE_DIR: '../datasets/thumos14/features/tsn_env_features/'
  AGENT_FEATURE_DIR: '../datasets/thumos14/features/anet_trained_agent_features/'
  CLASSIFICATION_PATH: 'results/uNet_test.npy'
  RESULT_PATH: 'results/results.pkl'
  TEMPORAL_DIM: 128
  MAX_DURATION: 64
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/thumos_c3d_checkpoints/scores.json'
  CHECKPOINT_DIR: 'checkpoints/thumos_c3d_checkpoints/'
  AGENT_DIM: 2048
  ENV_DIM: 400
  ENV_HIDDEN_DIM: 512
  AGENT_HIDDEN_DIM: 512
  FEAT_DIM: 512
  TRANSFORMER_DIM: 512
  TOPK_AGENTS: 3
BMN:
  POST_PROCESS:
    MAX_PROPOSALS: 3000
    NUM_THREADS: 12
    USE_HARD_NMS: True
    HARD_NMS_THRESHOLD: 0.45
