MODE: 'validation'
EVAL_TYPE: 'proposal'
DATASET: 'thumos'
USE_ENV: True
USE_AGENT: False
GPU_IDS: [0, 1, 2, 3]
EVAL_SCORE: 'AR@100'
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 20
  BATCH_SIZE: 16
  STEP_PERIOD: 1
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  LOG_DIR: 'runs/thumos_c3d_runs/'
VAL:
  SPLIT: 'testing'
  BATCH_SIZE: 32
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 32
  #CHECKPOINT_PATH: 'checkpoints/thumos_c3d_checkpoints/checkpoint_13/best_AR@100.pth'
  CHECKPOINT_PATH: 'checkpoints/ablation_study/thumos14_envonly/best_AR@100.pth'
  #CHECKPOINT_PATH: 'checkpoints/ablation_study/thumos14_env+self_c3d/best_AR@100.pth'
  #CHECKPOINT_PATH: 'checkpoints/ablation_study/thumos14_env+hard_c3d/best_AR@100.pth'
DATA:
  ANNOTATION_FILE: '../datasets/new_thumos14/thumos_annotations/thumos_annotations_09.json'
  ENV_FEATURE_DIR: '../datasets/thumos14/features/tsn_env_features/'
  AGENT_FEATURE_DIR: '../datasets/thumos14/features/anet_trained_agent_features/'
  RESULT_PATH: 'results/results.pkl'
  TEMPORAL_DIM: 128
  MAX_DURATION: 64
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/thumos_c3d_checkpoints/scores.json'
  CHECKPOINT_DIR: 'checkpoints/thumos_c3d_checkpoints/'
  AGENT_DIM: 2048
  ENV_DIM: 400
  ENV_HIDDEN_DIM: 512
  AGENT_HIDDEN_DIM: 512
  FEAT_DIM: 512
  TRANSFORMER_DIM: 512
  TOPK_AGENTS: 3
BMN:
  POST_PROCESS:
    NUM_THREADS: 12
    MAX_PROPOSALS: 1100
    SOFT_NMS_ALPHA: 0.3
    SOFT_NMS_LOW_THRESHOLD: 0.65
    SOFT_NMS_HIGH_THRESHOLD: 0.65
