MODE: 'validation'
EVAL_TYPE: 'detection'
DATASET: 'thumos'
USE_ENV: True
USE_AGENT: True
USE_OBJ: True
GPU_IDS: [0, 1, 2, 3]
EVAL_SCORE: 'mAP'
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 20
  BATCH_SIZE: 16
  STEP_PERIOD: 1
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  LOG_DIR: 'runs/thumos_c3d_CLIP_runs_TAD/'
VAL:
  SPLIT: 'testing'
  BATCH_SIZE: 16
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 16
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_4/best_AR@100.pth'
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT2/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_6/best_AR@100.pth'
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT2/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_7/best_AR@100.pth' #### SOFT train lan 2
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints_TAD/checkpoint_7/best_mAP.pth' ## best old

  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_4/best_AR@100.pth' ## THUMOS TAPG 1
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_5/best_AR@100.pth' ## THUMOS TAPG 2
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_6/best_AR@100.pth' ## THUMOS TAPG 3
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_8/best_AR@100.pth' ## THUMOS TAPG 4
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT2/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_6/best_AR@100.pth' ## THUMOS TAPG 5
  # CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT2/checkpoints/thumos_c3d_CLIP_checkpoints/checkpoint_7/best_AR@100.pth' ## THUMOS TAPG 6

  CHECKPOINT_PATH: '/home/ngan_uark/tqsang/AEN_BERT/checkpoints/thumos_c3d_CLIP_checkpoints_TAD/checkpoint_7/best_mAP.pth' ## THUMOS TAD 1

DATA:
  ANNOTATION_FILE: '/data/tqsang/thumos_annotations_09.json'
  DETECTION_GT_FILE: '/home/ngan_uark/tqsang/AEN_BERT/thumos_det_gt.json'
  ENV_FEATURE_DIR: '/data/tqsang/tsn_env_features/'
  AGENT_FEATURE_DIR: '/data/tqsang/anet_trained_agent_features/'
  OBJ_FEATURE_DIR: '/data/tqsang/CLIP_THUMOS_output_ft/'
  CLASSIFICATION_PATH: 'results/uNet_test.npy'
  RESULT_PATH: 'results/results_TAPG_6.pkl'
  TEMPORAL_DIM: 128
  MAX_DURATION: 64
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/thumos_c3d_CLIP_checkpoints_TAD/scores.json'
  CHECKPOINT_DIR: 'checkpoints/thumos_c3d_CLIP_checkpoints_TAD/'
  AGENT_DIM: 2048
  ENV_DIM: 400
  OBJ_DIM: 512
  OBJ_HIDDEN_DIM: 512
  ENV_HIDDEN_DIM: 512
  AGENT_HIDDEN_DIM: 512
  FEAT_DIM: 512
  TRANSFORMER_DIM: 512
  TOPK_AGENTS: 3
BMN:
  POST_PROCESS:
    MAX_PROPOSALS: 3000
    NUM_THREADS: 12
    USE_HARD_NMS: False
    HARD_NMS_THRESHOLD: 0.45
    SOFT_NMS_ALPHA: 0.4
    SOFT_NMS_LOW_THRESHOLD: 0.
    SOFT_NMS_HIGH_THRESHOLD: 0.

